### ISSUE TITLE
reports-summary.cgi is unable to take data for latest versions

### ISSUE THREAD

**Issue by polettix** [barbie/cpan-testers-www-reports#2]
Program [reports-summary.cgi](https://github.com/barbie/cpan-testers-www-reports/blob/master/vhost/cgi-bin/reports-summary.cgi) seems to be unable to take data for latest versions of a few distributions (I suspect it applies to every distribution but I'm not sure). For example, you can take a look at the following report in JSON format for [Data::Money](http://www.cpantesters.org/cgi-bin/reports-summary.cgi?_u=1454677534441&_fields=dist_pref&_fields=perlmat_pref&_fields=patches_pref&_fields=oncpan_pref&_fields=distmat_pref&_fields=perlver_pref&_fields=osname_pref&dist_pref=Data-Money&perlmat_pref=1&patches_pref=1&oncpan_pref=1&distmat_pref=1&perlver_pref=ALL&osname_pref=ALL&_event_type=ajax&format=json).

The elements in the report are not properly populated. I don't know what it depends on (I can't see the raw data in the database), probably something to do with the SQL query at line 355 or skipping at lines 369-372.

I'd guess this has also a bad effect on [meta::cpan](https://metacpan.org), because the "Testers" line on the left does not show the useful PASS/FAIL/NA count. E.g. compare [Template::Perlish 1.21](https://metacpan.org/release/POLETTIX/Template-Perlish-1.21)

<img width="148" alt="template-perlish-1.21" src="https://cloud.githubusercontent.com/assets/114540/12848709/ce519eb8-cc1b-11e5-9212-58ab955eae07.png">

against [Template::Perlish 1.50](https://metacpan.org/release/Template-Perlish)

<img width="146" alt="template-perlish-1.50" src="https://cloud.githubusercontent.com/assets/114540/12848741/f4ff77f6-cc1b-11e5-8842-0d5418a462cb.png">

**Comment by moocow-the-bovine** [comment]
Possibly related problem: [my cpantesters author page](http://www.cpantesters.org/author/M/MOOCOW.html) "report summary" / "distribution summary" section does not display the green+yellow+red status bars for any of my distributions updated after 2015-08-21. Looking at Chris Marshall's PDL distribution on metacpan, the "Testers" summary is populated for [PDL-2.012_01](https://metacpan.org/release/CHM/PDL-2.012_01) from 2015-08-01 but not for [PDL-2.013](https://metacpan.org/release/CHM/PDL-2.013) from 2015-08-14, [Chris's author page](http://www.cpantesters.org/author/C/CHM.html) is also missing status bars for the PDL distribution.  For the cpantesters site, it looks as if the `[% IF s.ALL %]` check at [line 31 of cpan-testers-www-reports/vhost/cgi-bin/templates/cpan/box-summary-static.html](https://github.com/barbie/cpan-testers-www-reports/blob/master/vhost/cgi-bin/templates/cpan/box-summary-static.html#L31) is failing, although being unfamiliar with the system, I can't tell why.

**Comment by polettix** [comment]
Is it possible to have a glimpse at the data in the database, so that we can propose a meaningful PR for this issue? It seems that the relevant exports are not published any more, or I'm possibly looking in the wrong place.

**Comment by polettix** [comment]
Trying to shoot in the dark, I went in [this page](http://devel.cpantesters.org/) and downloaded the [CPAN Testers Release Summary Database](http://devel.cpantesters.org/release/release.db.gz) (gzip format, as of today about 10 MB compressed and about 27 MB).

The data are missing from the database. They're not shown because they are not there.

This issue might belong to [CPAN-Testers-Data-Release](https://github.com/barbie/CPAN-Testers-Data-Release) instead.

**Comment by preaction** [comment]
The metacpan part is likely due to a release.db SQLite database that was previously being generated but no longer. It was deprecated and removed, but metacpan.org still relied on it for data. See https://github.com/CPAN-API/metacpan-web/issues/1630 for the metacpan issue tracking this problem.

The green/yellow/red status bar is related, as they're approximately the same data (the status bars use the data that then gets collected into the release.db SQLite database). Barbie is working on it here at the QAH and it should be fixed soon.

**Comment by polettix** [comment]
Amazing! I tried to contact Barbie to try and help but I did not get an answer... and I was too shy to insist.

**Comment by preaction** [comment]
This appears to be fixed now, though maybe not the metacpan part. Could you confirm?

**Comment by polettix** [comment]
Seems fine, although I initially got error "503". [Log::Log4perl::Tiny](https://metacpan.org/release/Log-Log4perl-Tiny) seems fine on metacpan too, maybe other modules will catch up later. Thanks!
