### ISSUE TITLE
Distro Building is taking too long

### ISSUE THREAD

**Issue by barbie** [barbie/cpan-testers-www-reports#5]
The Problem:

The builder for DistroPages can take a long time to run for a single distribution.

Adding some progress tracking lines to the code, gave me the following example (based on Version 1 code below):

    2017/05/30 09:16:20 .. .. starting PadWalker
    2017/05/30 09:16:20 .. .. getting records for PadWalker
    2017/05/30 09:16:20 .. .. retrieved records for PadWalker 
    2017/05/30 09:16:20 .. .. loading JSON data for PadWalker
    2017/05/30 09:16:21 .. .. loaded JSON data for PadWalker
    2017/05/30 09:16:24 .. .. starting data update for PadWalker
    2017/05/30 09:16:24 .. .. summary data update complete for PadWalker
    2017/05/30 09:16:24 .. .. version data update complete for PadWalker
    2017/05/30 09:27:27 .. .. OS data update complete for PadWalker
    2017/05/30 09:37:00 .. .. Pass Stats data update complete for PadWalker
    2017/05/30 09:37:01 .. .. memory data update complete for PadWalker
    2017/05/30 09:37:01 .. .. summary data stored for PadWalker
    2017/05/30 09:37:01 .. .. building static pages for PadWalker
    2017/05/30 09:37:02 .. .. Dynamic HTML page written for PadWalker
    2017/05/30 09:37:04 .. .. JS page written for PadWalker
    2017/05/30 09:37:04 .. .. JSON page written for PadWalker
    2017/05/30 09:37:04 .. .. Static HTML page written for PadWalker
    2017/05/30 09:37:06 .. .. removing page_request entries for PadWalker

As you can see the sticking points are loading the OS data and the Pass stats data. These lines amount to Version 1 code below

----

Version 1 Code: (taken from Labyrinth/Plugin/CPAN/Builder.pm, lines 736-752)

            my ($stats,$oses);
            @rows = $dbi->GetQuery('hash','GetDistrosPass',{dist=>$dist});
            for(@rows) {
                my ($osname,$code) = $cpan->OSName($_->{osname});
                $stats->{$_->{perl}}{$code}{count} = $_->{count};
                $oses->{$code} = $osname;
            }
    $progress->( ".. .. OS data update complete for $name" ) if(defined $progress);

            # distribution PASS stats
            my @stats = $dbi->GetQuery('hash','GetStatsPass',{dist=>$dist});
            for(@stats) {
                my ($osname,$code) = $cpan->OSName($_->{osname});
                $stats->{$_->{perl}}{$code}{version} = $_->{version}
                    if(!$stats->{$_->{perl}}->{$code} || _versioncmp($_->{version},$stats->{$_->{perl}}->{$code}{version}));
            }
    $progress->( ".. .. Pass Stats data update complete for $name" ) if(defined $progress);

----

These use the following 2 queries:

    GetDistrosPass=SELECT perl, osname, count(*) AS count FROM cpanstats.cpanstats WHERE dist IN ('$dist') AND state = 'pass' GROUP BY perl, osname
    GetStatsPass=SELECT perl, osname, version FROM cpanstats.cpanstats WHERE dist IN ('$dist') AND state='pass'

The GROUP BY is particularly painful, as the two fields 'perl' and 'osname' are not indexed.

However, the two requests are essentially requesting similar information in two subtly different ways. So a first optimisation was to simplify the request and use a single loop to store the data. This resulted in Version 2 code below.

----

Version 2 Code:

            # retrieve perl/os stats
            my ($stats,$oses);
            my @stats = $dbi->GetQuery('hash','GetStatsPass',$name);
            for(@stats) {
                my ($osname,$code) = $cpan->OSName($_->{osname});
                $stats->{$_->{perl}}{$code}{version} = $_->{version}
                    if(!$stats->{$_->{perl}}->{$code} || _versioncmp($_->{version},$stats->{$_->{perl}}->{$code}{version}));

                $stats->{$_->{perl}}{$code}{count}++;
                $oses->{$code} = $osname;
            }

----

This did improve things, but not by as big a margin as I would have hoped. Some queries for new or recent distributions were quick anyway, so this was something that needed assessing with older distributions. One such example was 'Math-BigInt'. Looking at the potential result set, we can see this would return 84,956 rows to process, which took 21 minutes to process!

    mysql> explain SELECT perl, osname, version FROM cpanstats.cpanstats WHERE dist IN ('Math-BigInt') AND state='pass';
    +----+-------------+-----------+------------+------+-------------------------------------+----------------------+---------+-------------+-------+----------+-------+
    | id | select_type | table     | partitions | type | possible_keys                       | key                  | key_len | ref         | rows  | filtered | Extra |
    +----+-------------+-----------+------------+------+-------------------------------------+----------------------+---------+-------------+-------+----------+-------+
    |  1 | SIMPLE      | cpanstats | NULL       | ref  | distvers,state,cpanstats_dist_state | cpanstats_dist_state | 293     | const,const | 84956 |   100.00 | NULL  |
    +----+-------------+-----------+------------+------+-------------------------------------+----------------------+---------+-------------+-------+----------+-------+

In other areas of CPAN Testers, particularly CPAN Statistics website, due to these large dataset lookups, storing summary information is needed to avoid overloading the database, and to speed up processing time.

Likewise, this area could also benefit from a summary storage, and updating only those records added since the last dist build would mean a smaller dataset is processed every time for all distributions.

As such, I would like to propose a new table to be used, with new queries and a Version 3 code block to replace the blocks used above.

----

New Table:

    CREATE TABLE stats_store (
      `dist`    varchar(255) NOT NULL,
      `version` varchar(255) DEFAULT NULL,
      `perl`    varchar(255) DEFAULT NULL,
      `oscode`  varchar(255) DEFAULT NULL,
      `counter` int(10) unsigned NOT NULL,
      `lastid`  int(10) unsigned NOT NULL,
      KEY `dist` (`dist`),
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

New Queries:

    GetStatsStore=SELECT * FROM cpanstats.stats_store WHERE dist=?
    DelStatsStore=DELETE FROM cpanstats.stats_store WHERE dist=?
    SetStatsStore=INSERT INTO cpanstats.stats_store (dist,perl,oscode,version,counter,lastid) VALUES (?,?,?,?,?,?)
    GetStatsPass2=SELECT perl, osname, version FROM cpanstats.cpanstats WHERE dist IN ('$dist') AND state='pass' AND id>?

----

Version 3 Code:

            # retrieve perl/os stats
            my ($stats,$oses);
            my $lastid = 0;
            my @rows = $dbi->GetQuery('hash','GetStatsStore',{dist=>$dist});
            for(@rows) {
                $stats->{$_->{perl}}{$_->{oscode}}{version} = $_->{version};
                $stats->{$_->{perl}}{$_->{oscode}}{count}   = $_->{counter};
                $oses->{$_->{oscode}} = $osname;
                $lastid |= $_->{lastid};
            }

            my @stats = $dbi->GetQuery('hash','GetStatsPass2',{dist=>$dist},$lastid);
            for(@stats) {
                my ($osname,$code) = $cpan->OSName($_->{osname});
                $stats->{$_->{perl}}{$code}{version} = $_->{version}
                    if(!$stats->{$_->{perl}}->{$code} || _versioncmp($_->{version},$stats->{$_->{perl}}->{$code}{version}));

                $stats->{$_->{perl}}{$code}{count}++;
                $oses->{$code} = $osname;
                $lastid = $_->{id} if($lastid < $_->{id};
            }

            $dbi->DoQuery('DelStatsStore',$name);
            for my $perl (keys %$stats) {
                for my $code (keys %{$stats->{$perl}}) {
                    $dbi->DoQuery('SetStatsStore',$name,$perl,$code,$stats->{$perl}{$code}{version},$stats->{$perl}{$code}{count},$lastid);
                }
            }

----

Note that none of this is live, and I'm not able to test with large datasets, so this may not be as big a benefit as it might appear on paper. However, I would be interested to hear thoughts about this, as to whether this would be worth tackling.

It would mean updating just Builder.pm for the code, and phrasebook.ini for the queries. As such I should be able to do a small release of CPAN-Testers-WWW-Reports. However, if the current builder processes are being rewritten, a note should be added there to capture this change.

**Comment by barbie** [comment]
@preaction & @glasswalk3r, would be interested in your reactions to this, seeing as you're working on improving the web and API interfaces.

**Comment by preaction** [comment]
My first thought is "This is a major problem right now and we should fix it however we can" and this seems like a good way to do that. My second thought is that it looks very similar to both the release summary table and the Matrix, and we might be able to make this new table serve those roles too if we add individual columns for pass/fail/na/unknown reports (reducing the amount of data the mysqld needs to keep in-memory by reducing the number of tables we have). So, yes, I think this is a good idea to improve performance.

We just had a speaker at Chicago.PM on MySQL InnoDB performance: For performance reasons, it will be good to make those `VARCHAR` columns as small as possible (`VARCHAR(10)` for `perl`, for example), and for InnoDB, it's apparently super-important to always have a plain integer auto-increment ID as the primary key (because all secondary index lookups are done by primary key, so the smaller that primary key is, the less memory is used up). Will `oscode` be the `osname` column from the `cpanstats` table or a combination of `osname` and `osvers`?

**Comment by barbie** [comment]
The release_summary (and release_data) serve a different purpose, and after reviewing a possible merging with new table, this would likely complicate the usage, and add more work to get their required end result sets. Although I do understand the balance for reducing the memory footprint.

The other problem with merging with the release tables, is that current release tables only get updated a few times a day. The new summary would need to be updated as reports are processed by the builder. This would then require the builder to process that information too. At the moment this only takes 10 minutes to do the updates, as the SELECT-loop-UPDATE/INSERT cycle is relatively simple. Adding this to the code to selectively update per distribution would likely add a significant overhead, as the higher profile distributions would get many more updates than currently. That's not necessarily a bad thing, but the current release data being out of date by a few hours isn't currently cause problems. Perhaps a merge could be revisited at some point in the future. 

No problem reducing the varchars, and these do make sense. 

Although we could create an auto-incrementing primary key, due to the nature of deleting old records and inserting new ones (far better performance over updates), these ids will get big very quickly. This table isn't meant to be used to lookup back to reports, just the dists. In fact the true primary key is (dist,version,perl,oscode), but the retrieval only (currently) needs to reference the dist to get a block of records at a time, hence only having a KEY (dist), reducing the overhead of keeping indexes that aren't used.

oscode is the same as osname.osname. I'll change it to osname though. I'd forgotten that the full name is referenced as osname.ostitle.

Doing some checks:

MAX length(dist) = 114 "Acme-Working-Out-Dependencies-From-META-yml-Or-META-json-Will-Be-Wrong-At-Some-Point-Like-This-Module-For-Instance"
MAX length(version) = 104 "1.08-withoutworldwriteables-generated-by-the-silly-pseudosecurity-measure-devised-to-piss-off-nonunixers"
MAX length(perl) = 106 "5.11.0 patch blead 2009-02-05.22:06:19 c8f794576f0d940fc66e0fc10236a1b54a7e40a3 GitLive-blead-510-gc8f7945"

However, the longest short form of the perl version is 7 characters. Thinking about it there is no good reason to use the long form version, and using the short form will simplify the output and reduce the storage needs.

----

Revised table:

    CREATE TABLE stats_store (
      `dist`    varchar(150) NOT NULL,
      `version` varchar(150) DEFAULT NULL,
      `perl`    varchar(10) DEFAULT NULL,
      `oscode`  varchar(32) DEFAULT NULL,
      `counter` int(10) unsigned NOT NULL,
      `lastid`  int(10) unsigned NOT NULL,
      KEY `dist` (`dist`),
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

**Comment by preaction** [comment]
Wow. What jerks made dists and versions like that? :p And that Perl version? (no need to answer my incredulity)

And yeah, I wasn't saying we should make it also do the release table right now while there's an urgent problem to solve, just that we might find a way to consolidate things in the future. My long-term plan is still to move to stream-based, real-time processing of reports as they come in, which could change the performance impact for some of the derived data like this.

**Comment by barbie** [comment]
Okay if you're happy with the table for now, and the code, I'll implement this weekend. 

The stream-based scenario would be much nicer. I would suggest pushing to queue based streams, with each focused on specific update processes, e.g. the release data, json builders, etc. Using a micro-service architecture you can then spin up listeners to process in parallel, which is the biggest pain with the builders at the moment, as you can only have the two process streams (distro & author) :(

**Comment by preaction** [comment]
Yep! That's the plan ;) I wrote [Beam::Runner](http://metacpan.org/pod/Beam::Runner) and [Beam::Minion](http://metacpan.org/pod/Beam::Minion) to help achieve that (and am giving a talk on it at The Perl Conference in a couple weeks). Every backend process is a module, and each module can be run on a command line with `beam run` or parallelized with `beam minion run`. And then we have some listeners on the APIs that emit events over the websocket server [Mercury](http://metacpan.org/pod/mercury) to trigger the Beam::Minion jobs, which each get placed on a different [Minion](http://metacpan.org/pod/Minion) queue.

**Comment by barbie** [comment]
Code is now live. Performance is currently the same as the last few days, but we're not likely to see the effects (and hopefully the benefits) until the bulk of regular tested distributions have had their stats stored.  Will keep an eye on things over the next few days.

**Comment by barbie** [comment]
After monitoring for a while, the performance isn't any worse than it was, but due to the volume entries that need to be created, we're not yet seeing the real benefits.

However, I've rethought the idea of an auto-incrementing key, as the current inserts are around 600+ per distribution. This is going to continue until all distributions have entries, but after that the massive inserts might be a burden. For example, once a distribution has it's stats stored, after loading it may have to loop through 400 reports before saving again. However, rather than inserting 600+ records, it may only need to update 50 (or likely less). 

As such, I'm going to look at slightly restructuring the storage to update/insert as appropriate.

This amendment won't affect the current running as we still need to insert data for several thousand distros still :)

**Comment by barbie** [comment]
After an uncertain start, the changes are starting to have an effect. The outstanding entries have been steadily declining since the change have been made, but in the last few days the momentum has started to increase. 

We're still a month behind, but the pace at which the build is working through the backlog is finally starting to improve. It may still take a few weeks to get back to reports being processed within the day, but the numbers are at least moving in the right direction.

Will continue to monitor over the next few weeks.

**Comment by barbie** [comment]
We're now back to pages/files being built within 24 hours .. currently within 8 hours ... so closing this ticket.
